mostly improved code readability

diff --git a/functions/_mf_define b/functions/_mf_define
--- a/functions/_mf_define
+++ b/functions/_mf_define
@@ -1,11 +1,25 @@
-[[ $EDITOR == *vim ]] &&
-    local ftopts="-c 'set ft=zsh'" ||
-[[ $EDITOR == *micro ]] &&
+if [[ $EDITOR == *vim ]]
+then
+    local ftopts="-c 'set ft=zsh'"
+elif [[ $EDITOR == *micro ]]
+then
     local ftopts="-filetype=zsh"
-eval $EDITOR "$ftopts" "${MFUNCDIR}/$1"  &&
-    [[ -f "${MFUNCDIR}/$1" ]] &&
-        autoload $1 || {
-            echo "aborting..."
-            return 1
-        }
-$edit || echo "new function '$1' created in $MFUNCDIR"
+fi
+
+eval $EDITOR "$ftopts" "${MFUNCDIR}/$1"
+
+if ! [[ -f "${MFUNCDIR}/$1" ]]
+then
+    echo "aborting..."
+    return 1
+else
+    $commands[${1}] && unfunction $1 # just in case
+    autoload $1
+fi
+
+if $edit
+then
+    echo "updated function '${1}'"
+else
+    echo "new function '${1}' created in $MFUNCDIR"
+fi
